# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

build docker image:
  stage: build
  image: docker:latest
  services:
    - docker:stable-dind
  before_script:
    - docker version
  script:
    - docker build -t ceah-backend . --no-cache

lint:
  stage: test
  before_script:
    - python -V  # Print out python version for debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
  script:
    - pip install flake8
    - flake8 --ignore=E501 *.py

deploy digitalocean:
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_KEY")
    - mkdir -p ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh root@app.markturner.uk "cd ceah-backend && git stash && git pull && sh build.sh"
    - ssh root@app.markturner.uk DB_USERNAME=$DB_USERNAME DB_PASSWORD=$DB_PASSWORD "docker run -p 1701:1701 -e DB_USERNAME=$DB_USERNAME -e DB_PASSWORD=$DB_PASSWORD -d --name ceah-backend ceah-backend"
  only:
    - master
